### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by faf** [Mibew/google-maps-plugin#3]
We need to add support for IPv6 addresses.

**Comment by faf** [comment]
@everyx Could you check, if it's work for you with the latest related changes in Mibew itself?

**Comment by everyx** [comment]
@faf OK, I will replace it at toady night, but I'm not sure my site will have a ipv6 visitor at the same time, so maybe we will waitting for some days :)

**Comment by everyx** [comment]
@faf A IPv6 visitor is comed today, and everything work great, thanks for you working. :)

**Comment by faf** [comment]
@everyx Great. Then we'll release the new Mibew Messenger and this plugin at the same time. Probably in the next few days.
